// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MarsPioneerProto.proto

package com.example.marspioneer.proto;

/**
 * Protobuf type {@code com.example.marspioneer.proto.BuildingEntityProto}
 */
public final class BuildingEntityProto extends
    com.google.protobuf.GeneratedMessageV3 implements com.nkasenides.athlos.proto.Modelable<com.example.marspioneer.model.BuildingEntity> , com.nkasenides.athlos.model.IEntity, 
    // @@protoc_insertion_point(message_implements:com.example.marspioneer.proto.BuildingEntityProto)
    BuildingEntityProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BuildingEntityProto.newBuilder() to construct.
  private BuildingEntityProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BuildingEntityProto() {
    worldID_ = "";
    id_ = "";
    buildingType_ = 0;
    playerID_ = "";
    direction_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BuildingEntityProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BuildingEntityProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            worldID_ = s;
            break;
          }
          case 21: {

            areaOfInterest_ = input.readFloat();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 34: {
            com.example.marspioneer.proto.MatrixPositionProto.Builder subBuilder = null;
            if (position_ != null) {
              subBuilder = position_.toBuilder();
            }
            position_ = input.readMessage(com.example.marspioneer.proto.MatrixPositionProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(position_);
              position_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            buildingType_ = rawValue;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            playerID_ = s;
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            direction_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_BuildingEntityProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_BuildingEntityProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.marspioneer.proto.BuildingEntityProto.class, com.example.marspioneer.proto.BuildingEntityProto.Builder.class);
  }

  public static final int WORLDID_FIELD_NUMBER = 1;
  private volatile java.lang.Object worldID_;
  /**
   * <code>string worldID = 1;</code>
   * @return The worldID.
   */
  @java.lang.Override
  public java.lang.String getWorldID() {
    java.lang.Object ref = worldID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      worldID_ = s;
      return s;
    }
  }
  /**
   * <code>string worldID = 1;</code>
   * @return The bytes for worldID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWorldIDBytes() {
    java.lang.Object ref = worldID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      worldID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AREAOFINTEREST_FIELD_NUMBER = 2;
  private float areaOfInterest_;
  /**
   * <code>float areaOfInterest = 2;</code>
   * @return The areaOfInterest.
   */
  @java.lang.Override
  public float getAreaOfInterest() {
    return areaOfInterest_;
  }

  public static final int ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 3;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 3;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_FIELD_NUMBER = 4;
  private com.example.marspioneer.proto.MatrixPositionProto position_;
  /**
   * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 4;</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return position_ != null;
  }
  /**
   * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 4;</code>
   * @return The position.
   */
  @java.lang.Override
  public com.example.marspioneer.proto.MatrixPositionProto getPosition() {
    return position_ == null ? com.example.marspioneer.proto.MatrixPositionProto.getDefaultInstance() : position_;
  }
  /**
   * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 4;</code>
   */
  @java.lang.Override
  public com.example.marspioneer.proto.MatrixPositionProtoOrBuilder getPositionOrBuilder() {
    return getPosition();
  }

  public static final int BUILDINGTYPE_FIELD_NUMBER = 5;
  private int buildingType_;
  /**
   * <code>.com.example.marspioneer.proto.EBuildingType buildingType = 5;</code>
   * @return The enum numeric value on the wire for buildingType.
   */
  @java.lang.Override public int getBuildingTypeValue() {
    return buildingType_;
  }
  /**
   * <code>.com.example.marspioneer.proto.EBuildingType buildingType = 5;</code>
   * @return The buildingType.
   */
  @java.lang.Override public com.example.marspioneer.proto.EBuildingType getBuildingType() {
    @SuppressWarnings("deprecation")
    com.example.marspioneer.proto.EBuildingType result = com.example.marspioneer.proto.EBuildingType.valueOf(buildingType_);
    return result == null ? com.example.marspioneer.proto.EBuildingType.UNRECOGNIZED : result;
  }

  public static final int PLAYERID_FIELD_NUMBER = 6;
  private volatile java.lang.Object playerID_;
  /**
   * <code>string playerID = 6;</code>
   * @return The playerID.
   */
  @java.lang.Override
  public java.lang.String getPlayerID() {
    java.lang.Object ref = playerID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      playerID_ = s;
      return s;
    }
  }
  /**
   * <code>string playerID = 6;</code>
   * @return The bytes for playerID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlayerIDBytes() {
    java.lang.Object ref = playerID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      playerID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECTION_FIELD_NUMBER = 7;
  private int direction_;
  /**
   * <code>.com.example.marspioneer.proto.Direction4 direction = 7;</code>
   * @return The enum numeric value on the wire for direction.
   */
  @java.lang.Override public int getDirectionValue() {
    return direction_;
  }
  /**
   * <code>.com.example.marspioneer.proto.Direction4 direction = 7;</code>
   * @return The direction.
   */
  @java.lang.Override public com.example.marspioneer.proto.Direction4 getDirection() {
    @SuppressWarnings("deprecation")
    com.example.marspioneer.proto.Direction4 result = com.example.marspioneer.proto.Direction4.valueOf(direction_);
    return result == null ? com.example.marspioneer.proto.Direction4.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWorldIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, worldID_);
    }
    if (areaOfInterest_ != 0F) {
      output.writeFloat(2, areaOfInterest_);
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, id_);
    }
    if (position_ != null) {
      output.writeMessage(4, getPosition());
    }
    if (buildingType_ != com.example.marspioneer.proto.EBuildingType.HUB_EBuildingType.getNumber()) {
      output.writeEnum(5, buildingType_);
    }
    if (!getPlayerIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, playerID_);
    }
    if (direction_ != com.example.marspioneer.proto.Direction4.NORTH.getNumber()) {
      output.writeEnum(7, direction_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWorldIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, worldID_);
    }
    if (areaOfInterest_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, areaOfInterest_);
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, id_);
    }
    if (position_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getPosition());
    }
    if (buildingType_ != com.example.marspioneer.proto.EBuildingType.HUB_EBuildingType.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, buildingType_);
    }
    if (!getPlayerIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, playerID_);
    }
    if (direction_ != com.example.marspioneer.proto.Direction4.NORTH.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, direction_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.marspioneer.proto.BuildingEntityProto)) {
      return super.equals(obj);
    }
    com.example.marspioneer.proto.BuildingEntityProto other = (com.example.marspioneer.proto.BuildingEntityProto) obj;

    if (!getWorldID()
        .equals(other.getWorldID())) return false;
    if (java.lang.Float.floatToIntBits(getAreaOfInterest())
        != java.lang.Float.floatToIntBits(
            other.getAreaOfInterest())) return false;
    if (!getId()
        .equals(other.getId())) return false;
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (buildingType_ != other.buildingType_) return false;
    if (!getPlayerID()
        .equals(other.getPlayerID())) return false;
    if (direction_ != other.direction_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WORLDID_FIELD_NUMBER;
    hash = (53 * hash) + getWorldID().hashCode();
    hash = (37 * hash) + AREAOFINTEREST_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAreaOfInterest());
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    hash = (37 * hash) + BUILDINGTYPE_FIELD_NUMBER;
    hash = (53 * hash) + buildingType_;
    hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerID().hashCode();
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + direction_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.marspioneer.proto.BuildingEntityProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.marspioneer.proto.BuildingEntityProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.marspioneer.proto.BuildingEntityProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.marspioneer.proto.BuildingEntityProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.marspioneer.proto.BuildingEntityProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.marspioneer.proto.BuildingEntityProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.marspioneer.proto.BuildingEntityProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.marspioneer.proto.BuildingEntityProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.marspioneer.proto.BuildingEntityProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.marspioneer.proto.BuildingEntityProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.marspioneer.proto.BuildingEntityProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.marspioneer.proto.BuildingEntityProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.marspioneer.proto.BuildingEntityProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.marspioneer.proto.BuildingEntityProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements com.nkasenides.athlos.model.IEntity, com.nkasenides.athlos.proto.Modelable<com.example.marspioneer.model.BuildingEntity>, 
      // @@protoc_insertion_point(builder_implements:com.example.marspioneer.proto.BuildingEntityProto)
      com.example.marspioneer.proto.BuildingEntityProtoOrBuilder {    @java.lang.Override    
    public com.example.marspioneer.model.BuildingEntity toObject() {    
        com.example.marspioneer.model.BuildingEntity item = new com.example.marspioneer.model.BuildingEntity();        
        item.setWorldID(getWorldID());        
        item.setAreaOfInterest(getAreaOfInterest());        
        item.setId(getId());        
        item.setPosition(getPosition().toObject());        
        item.setBuildingType(getBuildingType());        
        item.setPlayerID(getPlayerID());        
        item.setDirection(getDirection());        
        return item;        
    }    
    

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_BuildingEntityProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_BuildingEntityProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.marspioneer.proto.BuildingEntityProto.class, com.example.marspioneer.proto.BuildingEntityProto.Builder.class);
    }

    // Construct using com.example.marspioneer.proto.BuildingEntityProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      worldID_ = "";

      areaOfInterest_ = 0F;

      id_ = "";

      if (positionBuilder_ == null) {
        position_ = null;
      } else {
        position_ = null;
        positionBuilder_ = null;
      }
      buildingType_ = 0;

      playerID_ = "";

      direction_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_BuildingEntityProto_descriptor;
    }

    @java.lang.Override
    public com.example.marspioneer.proto.BuildingEntityProto getDefaultInstanceForType() {
      return com.example.marspioneer.proto.BuildingEntityProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.marspioneer.proto.BuildingEntityProto build() {
      com.example.marspioneer.proto.BuildingEntityProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.marspioneer.proto.BuildingEntityProto buildPartial() {
      com.example.marspioneer.proto.BuildingEntityProto result = new com.example.marspioneer.proto.BuildingEntityProto(this);
      result.worldID_ = worldID_;
      result.areaOfInterest_ = areaOfInterest_;
      result.id_ = id_;
      if (positionBuilder_ == null) {
        result.position_ = position_;
      } else {
        result.position_ = positionBuilder_.build();
      }
      result.buildingType_ = buildingType_;
      result.playerID_ = playerID_;
      result.direction_ = direction_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.marspioneer.proto.BuildingEntityProto) {
        return mergeFrom((com.example.marspioneer.proto.BuildingEntityProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.marspioneer.proto.BuildingEntityProto other) {
      if (other == com.example.marspioneer.proto.BuildingEntityProto.getDefaultInstance()) return this;
      if (!other.getWorldID().isEmpty()) {
        worldID_ = other.worldID_;
        onChanged();
      }
      if (other.getAreaOfInterest() != 0F) {
        setAreaOfInterest(other.getAreaOfInterest());
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.buildingType_ != 0) {
        setBuildingTypeValue(other.getBuildingTypeValue());
      }
      if (!other.getPlayerID().isEmpty()) {
        playerID_ = other.playerID_;
        onChanged();
      }
      if (other.direction_ != 0) {
        setDirectionValue(other.getDirectionValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.marspioneer.proto.BuildingEntityProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.marspioneer.proto.BuildingEntityProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object worldID_ = "";
    /**
     * <code>string worldID = 1;</code>
     * @return The worldID.
     */
    public java.lang.String getWorldID() {
      java.lang.Object ref = worldID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        worldID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string worldID = 1;</code>
     * @return The bytes for worldID.
     */
    public com.google.protobuf.ByteString
        getWorldIDBytes() {
      java.lang.Object ref = worldID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        worldID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string worldID = 1;</code>
     * @param value The worldID to set.
     * @return This builder for chaining.
     */
    public Builder setWorldID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      worldID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string worldID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorldID() {
      
      worldID_ = getDefaultInstance().getWorldID();
      onChanged();
      return this;
    }
    /**
     * <code>string worldID = 1;</code>
     * @param value The bytes for worldID to set.
     * @return This builder for chaining.
     */
    public Builder setWorldIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      worldID_ = value;
      onChanged();
      return this;
    }

    private float areaOfInterest_ ;
    /**
     * <code>float areaOfInterest = 2;</code>
     * @return The areaOfInterest.
     */
    @java.lang.Override
    public float getAreaOfInterest() {
      return areaOfInterest_;
    }
    /**
     * <code>float areaOfInterest = 2;</code>
     * @param value The areaOfInterest to set.
     * @return This builder for chaining.
     */
    public Builder setAreaOfInterest(float value) {
      
      areaOfInterest_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float areaOfInterest = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAreaOfInterest() {
      
      areaOfInterest_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 3;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 3;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 3;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 3;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private com.example.marspioneer.proto.MatrixPositionProto position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.marspioneer.proto.MatrixPositionProto, com.example.marspioneer.proto.MatrixPositionProto.Builder, com.example.marspioneer.proto.MatrixPositionProtoOrBuilder> positionBuilder_;
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 4;</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return positionBuilder_ != null || position_ != null;
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 4;</code>
     * @return The position.
     */
    public com.example.marspioneer.proto.MatrixPositionProto getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? com.example.marspioneer.proto.MatrixPositionProto.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 4;</code>
     */
    public Builder setPosition(com.example.marspioneer.proto.MatrixPositionProto value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
        onChanged();
      } else {
        positionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 4;</code>
     */
    public Builder setPosition(
        com.example.marspioneer.proto.MatrixPositionProto.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
        onChanged();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 4;</code>
     */
    public Builder mergePosition(com.example.marspioneer.proto.MatrixPositionProto value) {
      if (positionBuilder_ == null) {
        if (position_ != null) {
          position_ =
            com.example.marspioneer.proto.MatrixPositionProto.newBuilder(position_).mergeFrom(value).buildPartial();
        } else {
          position_ = value;
        }
        onChanged();
      } else {
        positionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 4;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        position_ = null;
        onChanged();
      } else {
        position_ = null;
        positionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 4;</code>
     */
    public com.example.marspioneer.proto.MatrixPositionProto.Builder getPositionBuilder() {
      
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 4;</code>
     */
    public com.example.marspioneer.proto.MatrixPositionProtoOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            com.example.marspioneer.proto.MatrixPositionProto.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.marspioneer.proto.MatrixPositionProto, com.example.marspioneer.proto.MatrixPositionProto.Builder, com.example.marspioneer.proto.MatrixPositionProtoOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.marspioneer.proto.MatrixPositionProto, com.example.marspioneer.proto.MatrixPositionProto.Builder, com.example.marspioneer.proto.MatrixPositionProtoOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private int buildingType_ = 0;
    /**
     * <code>.com.example.marspioneer.proto.EBuildingType buildingType = 5;</code>
     * @return The enum numeric value on the wire for buildingType.
     */
    @java.lang.Override public int getBuildingTypeValue() {
      return buildingType_;
    }
    /**
     * <code>.com.example.marspioneer.proto.EBuildingType buildingType = 5;</code>
     * @param value The enum numeric value on the wire for buildingType to set.
     * @return This builder for chaining.
     */
    public Builder setBuildingTypeValue(int value) {
      
      buildingType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.EBuildingType buildingType = 5;</code>
     * @return The buildingType.
     */
    @java.lang.Override
    public com.example.marspioneer.proto.EBuildingType getBuildingType() {
      @SuppressWarnings("deprecation")
      com.example.marspioneer.proto.EBuildingType result = com.example.marspioneer.proto.EBuildingType.valueOf(buildingType_);
      return result == null ? com.example.marspioneer.proto.EBuildingType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.example.marspioneer.proto.EBuildingType buildingType = 5;</code>
     * @param value The buildingType to set.
     * @return This builder for chaining.
     */
    public Builder setBuildingType(com.example.marspioneer.proto.EBuildingType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      buildingType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.EBuildingType buildingType = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuildingType() {
      
      buildingType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object playerID_ = "";
    /**
     * <code>string playerID = 6;</code>
     * @return The playerID.
     */
    public java.lang.String getPlayerID() {
      java.lang.Object ref = playerID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string playerID = 6;</code>
     * @return The bytes for playerID.
     */
    public com.google.protobuf.ByteString
        getPlayerIDBytes() {
      java.lang.Object ref = playerID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string playerID = 6;</code>
     * @param value The playerID to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      playerID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string playerID = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerID() {
      
      playerID_ = getDefaultInstance().getPlayerID();
      onChanged();
      return this;
    }
    /**
     * <code>string playerID = 6;</code>
     * @param value The bytes for playerID to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      playerID_ = value;
      onChanged();
      return this;
    }

    private int direction_ = 0;
    /**
     * <code>.com.example.marspioneer.proto.Direction4 direction = 7;</code>
     * @return The enum numeric value on the wire for direction.
     */
    @java.lang.Override public int getDirectionValue() {
      return direction_;
    }
    /**
     * <code>.com.example.marspioneer.proto.Direction4 direction = 7;</code>
     * @param value The enum numeric value on the wire for direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirectionValue(int value) {
      
      direction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.Direction4 direction = 7;</code>
     * @return The direction.
     */
    @java.lang.Override
    public com.example.marspioneer.proto.Direction4 getDirection() {
      @SuppressWarnings("deprecation")
      com.example.marspioneer.proto.Direction4 result = com.example.marspioneer.proto.Direction4.valueOf(direction_);
      return result == null ? com.example.marspioneer.proto.Direction4.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.example.marspioneer.proto.Direction4 direction = 7;</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(com.example.marspioneer.proto.Direction4 value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      direction_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.Direction4 direction = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      
      direction_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.marspioneer.proto.BuildingEntityProto)
  }

  // @@protoc_insertion_point(class_scope:com.example.marspioneer.proto.BuildingEntityProto)
  private static final com.example.marspioneer.proto.BuildingEntityProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.marspioneer.proto.BuildingEntityProto();
  }

  public static com.example.marspioneer.proto.BuildingEntityProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BuildingEntityProto>
      PARSER = new com.google.protobuf.AbstractParser<BuildingEntityProto>() {
    @java.lang.Override
    public BuildingEntityProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BuildingEntityProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BuildingEntityProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BuildingEntityProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.marspioneer.proto.BuildingEntityProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

    @java.lang.Override    
    public com.example.marspioneer.model.BuildingEntity toObject() {    
        com.example.marspioneer.model.BuildingEntity item = new com.example.marspioneer.model.BuildingEntity();        
        item.setWorldID(getWorldID());        
        item.setAreaOfInterest(getAreaOfInterest());        
        item.setId(getId());        
        item.setPosition(getPosition().toObject());        
        item.setBuildingType(getBuildingType());        
        item.setPlayerID(getPlayerID());        
        item.setDirection(getDirection());        
        return item;        
    }    
    
}

