// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MarsPioneerProto.proto

package com.example.marspioneer.proto;

public interface DeleteBuildingTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.marspioneer.proto.DeleteBuildingTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
   * @return Whether the gameSessionID field is set.
   */
  boolean hasGameSessionID();
  /**
   * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
   * @return The gameSessionID.
   */
  MPGameSessionProto getGameSessionID();
  /**
   * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
   */
  MPGameSessionProtoOrBuilder getGameSessionIDOrBuilder();

  /**
   * <code>string buildingTypeID = 2;</code>
   * @return The buildingTypeID.
   */
  String getBuildingTypeID();
  /**
   * <code>string buildingTypeID = 2;</code>
   * @return The bytes for buildingTypeID.
   */
  com.google.protobuf.ByteString
      getBuildingTypeIDBytes();
}
