// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MarsPioneerProto.proto

package com.example.marspioneer.proto;

/**
 * Protobuf type {@code com.example.marspioneer.proto.DeleteBuildingTypeRequest}
 */
public final class DeleteBuildingTypeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.marspioneer.proto.DeleteBuildingTypeRequest)
    DeleteBuildingTypeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeleteBuildingTypeRequest.newBuilder() to construct.
  private DeleteBuildingTypeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeleteBuildingTypeRequest() {
    buildingTypeID_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeleteBuildingTypeRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DeleteBuildingTypeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.example.marspioneer.proto.MPGameSessionProto.Builder subBuilder = null;
            if (gameSessionID_ != null) {
              subBuilder = gameSessionID_.toBuilder();
            }
            gameSessionID_ = input.readMessage(com.example.marspioneer.proto.MPGameSessionProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(gameSessionID_);
              gameSessionID_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            buildingTypeID_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_DeleteBuildingTypeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_DeleteBuildingTypeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.marspioneer.proto.DeleteBuildingTypeRequest.class, com.example.marspioneer.proto.DeleteBuildingTypeRequest.Builder.class);
  }

  public static final int GAMESESSIONID_FIELD_NUMBER = 1;
  private com.example.marspioneer.proto.MPGameSessionProto gameSessionID_;
  /**
   * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
   * @return Whether the gameSessionID field is set.
   */
  @java.lang.Override
  public boolean hasGameSessionID() {
    return gameSessionID_ != null;
  }
  /**
   * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
   * @return The gameSessionID.
   */
  @java.lang.Override
  public com.example.marspioneer.proto.MPGameSessionProto getGameSessionID() {
    return gameSessionID_ == null ? com.example.marspioneer.proto.MPGameSessionProto.getDefaultInstance() : gameSessionID_;
  }
  /**
   * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
   */
  @java.lang.Override
  public com.example.marspioneer.proto.MPGameSessionProtoOrBuilder getGameSessionIDOrBuilder() {
    return getGameSessionID();
  }

  public static final int BUILDINGTYPEID_FIELD_NUMBER = 2;
  private volatile java.lang.Object buildingTypeID_;
  /**
   * <code>string buildingTypeID = 2;</code>
   * @return The buildingTypeID.
   */
  @java.lang.Override
  public java.lang.String getBuildingTypeID() {
    java.lang.Object ref = buildingTypeID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      buildingTypeID_ = s;
      return s;
    }
  }
  /**
   * <code>string buildingTypeID = 2;</code>
   * @return The bytes for buildingTypeID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBuildingTypeIDBytes() {
    java.lang.Object ref = buildingTypeID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      buildingTypeID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (gameSessionID_ != null) {
      output.writeMessage(1, getGameSessionID());
    }
    if (!getBuildingTypeIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, buildingTypeID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (gameSessionID_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGameSessionID());
    }
    if (!getBuildingTypeIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, buildingTypeID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.marspioneer.proto.DeleteBuildingTypeRequest)) {
      return super.equals(obj);
    }
    com.example.marspioneer.proto.DeleteBuildingTypeRequest other = (com.example.marspioneer.proto.DeleteBuildingTypeRequest) obj;

    if (hasGameSessionID() != other.hasGameSessionID()) return false;
    if (hasGameSessionID()) {
      if (!getGameSessionID()
          .equals(other.getGameSessionID())) return false;
    }
    if (!getBuildingTypeID()
        .equals(other.getBuildingTypeID())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGameSessionID()) {
      hash = (37 * hash) + GAMESESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getGameSessionID().hashCode();
    }
    hash = (37 * hash) + BUILDINGTYPEID_FIELD_NUMBER;
    hash = (53 * hash) + getBuildingTypeID().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.marspioneer.proto.DeleteBuildingTypeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.marspioneer.proto.DeleteBuildingTypeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.marspioneer.proto.DeleteBuildingTypeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.marspioneer.proto.DeleteBuildingTypeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.marspioneer.proto.DeleteBuildingTypeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.marspioneer.proto.DeleteBuildingTypeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.marspioneer.proto.DeleteBuildingTypeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.marspioneer.proto.DeleteBuildingTypeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.marspioneer.proto.DeleteBuildingTypeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.marspioneer.proto.DeleteBuildingTypeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.marspioneer.proto.DeleteBuildingTypeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.marspioneer.proto.DeleteBuildingTypeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.marspioneer.proto.DeleteBuildingTypeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.marspioneer.proto.DeleteBuildingTypeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.marspioneer.proto.DeleteBuildingTypeRequest)
      com.example.marspioneer.proto.DeleteBuildingTypeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_DeleteBuildingTypeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_DeleteBuildingTypeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.marspioneer.proto.DeleteBuildingTypeRequest.class, com.example.marspioneer.proto.DeleteBuildingTypeRequest.Builder.class);
    }

    // Construct using com.example.marspioneer.proto.DeleteBuildingTypeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (gameSessionIDBuilder_ == null) {
        gameSessionID_ = null;
      } else {
        gameSessionID_ = null;
        gameSessionIDBuilder_ = null;
      }
      buildingTypeID_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_DeleteBuildingTypeRequest_descriptor;
    }

    @java.lang.Override
    public com.example.marspioneer.proto.DeleteBuildingTypeRequest getDefaultInstanceForType() {
      return com.example.marspioneer.proto.DeleteBuildingTypeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.marspioneer.proto.DeleteBuildingTypeRequest build() {
      com.example.marspioneer.proto.DeleteBuildingTypeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.marspioneer.proto.DeleteBuildingTypeRequest buildPartial() {
      com.example.marspioneer.proto.DeleteBuildingTypeRequest result = new com.example.marspioneer.proto.DeleteBuildingTypeRequest(this);
      if (gameSessionIDBuilder_ == null) {
        result.gameSessionID_ = gameSessionID_;
      } else {
        result.gameSessionID_ = gameSessionIDBuilder_.build();
      }
      result.buildingTypeID_ = buildingTypeID_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.marspioneer.proto.DeleteBuildingTypeRequest) {
        return mergeFrom((com.example.marspioneer.proto.DeleteBuildingTypeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.marspioneer.proto.DeleteBuildingTypeRequest other) {
      if (other == com.example.marspioneer.proto.DeleteBuildingTypeRequest.getDefaultInstance()) return this;
      if (other.hasGameSessionID()) {
        mergeGameSessionID(other.getGameSessionID());
      }
      if (!other.getBuildingTypeID().isEmpty()) {
        buildingTypeID_ = other.buildingTypeID_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.marspioneer.proto.DeleteBuildingTypeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.marspioneer.proto.DeleteBuildingTypeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.example.marspioneer.proto.MPGameSessionProto gameSessionID_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.marspioneer.proto.MPGameSessionProto, com.example.marspioneer.proto.MPGameSessionProto.Builder, com.example.marspioneer.proto.MPGameSessionProtoOrBuilder> gameSessionIDBuilder_;
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     * @return Whether the gameSessionID field is set.
     */
    public boolean hasGameSessionID() {
      return gameSessionIDBuilder_ != null || gameSessionID_ != null;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     * @return The gameSessionID.
     */
    public com.example.marspioneer.proto.MPGameSessionProto getGameSessionID() {
      if (gameSessionIDBuilder_ == null) {
        return gameSessionID_ == null ? com.example.marspioneer.proto.MPGameSessionProto.getDefaultInstance() : gameSessionID_;
      } else {
        return gameSessionIDBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     */
    public Builder setGameSessionID(com.example.marspioneer.proto.MPGameSessionProto value) {
      if (gameSessionIDBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gameSessionID_ = value;
        onChanged();
      } else {
        gameSessionIDBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     */
    public Builder setGameSessionID(
        com.example.marspioneer.proto.MPGameSessionProto.Builder builderForValue) {
      if (gameSessionIDBuilder_ == null) {
        gameSessionID_ = builderForValue.build();
        onChanged();
      } else {
        gameSessionIDBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     */
    public Builder mergeGameSessionID(com.example.marspioneer.proto.MPGameSessionProto value) {
      if (gameSessionIDBuilder_ == null) {
        if (gameSessionID_ != null) {
          gameSessionID_ =
            com.example.marspioneer.proto.MPGameSessionProto.newBuilder(gameSessionID_).mergeFrom(value).buildPartial();
        } else {
          gameSessionID_ = value;
        }
        onChanged();
      } else {
        gameSessionIDBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     */
    public Builder clearGameSessionID() {
      if (gameSessionIDBuilder_ == null) {
        gameSessionID_ = null;
        onChanged();
      } else {
        gameSessionID_ = null;
        gameSessionIDBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     */
    public com.example.marspioneer.proto.MPGameSessionProto.Builder getGameSessionIDBuilder() {
      
      onChanged();
      return getGameSessionIDFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     */
    public com.example.marspioneer.proto.MPGameSessionProtoOrBuilder getGameSessionIDOrBuilder() {
      if (gameSessionIDBuilder_ != null) {
        return gameSessionIDBuilder_.getMessageOrBuilder();
      } else {
        return gameSessionID_ == null ?
            com.example.marspioneer.proto.MPGameSessionProto.getDefaultInstance() : gameSessionID_;
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.marspioneer.proto.MPGameSessionProto, com.example.marspioneer.proto.MPGameSessionProto.Builder, com.example.marspioneer.proto.MPGameSessionProtoOrBuilder> 
        getGameSessionIDFieldBuilder() {
      if (gameSessionIDBuilder_ == null) {
        gameSessionIDBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.marspioneer.proto.MPGameSessionProto, com.example.marspioneer.proto.MPGameSessionProto.Builder, com.example.marspioneer.proto.MPGameSessionProtoOrBuilder>(
                getGameSessionID(),
                getParentForChildren(),
                isClean());
        gameSessionID_ = null;
      }
      return gameSessionIDBuilder_;
    }

    private java.lang.Object buildingTypeID_ = "";
    /**
     * <code>string buildingTypeID = 2;</code>
     * @return The buildingTypeID.
     */
    public java.lang.String getBuildingTypeID() {
      java.lang.Object ref = buildingTypeID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buildingTypeID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string buildingTypeID = 2;</code>
     * @return The bytes for buildingTypeID.
     */
    public com.google.protobuf.ByteString
        getBuildingTypeIDBytes() {
      java.lang.Object ref = buildingTypeID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buildingTypeID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string buildingTypeID = 2;</code>
     * @param value The buildingTypeID to set.
     * @return This builder for chaining.
     */
    public Builder setBuildingTypeID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      buildingTypeID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string buildingTypeID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuildingTypeID() {
      
      buildingTypeID_ = getDefaultInstance().getBuildingTypeID();
      onChanged();
      return this;
    }
    /**
     * <code>string buildingTypeID = 2;</code>
     * @param value The bytes for buildingTypeID to set.
     * @return This builder for chaining.
     */
    public Builder setBuildingTypeIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      buildingTypeID_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.marspioneer.proto.DeleteBuildingTypeRequest)
  }

  // @@protoc_insertion_point(class_scope:com.example.marspioneer.proto.DeleteBuildingTypeRequest)
  private static final com.example.marspioneer.proto.DeleteBuildingTypeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.marspioneer.proto.DeleteBuildingTypeRequest();
  }

  public static com.example.marspioneer.proto.DeleteBuildingTypeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeleteBuildingTypeRequest>
      PARSER = new com.google.protobuf.AbstractParser<DeleteBuildingTypeRequest>() {
    @java.lang.Override
    public DeleteBuildingTypeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DeleteBuildingTypeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeleteBuildingTypeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeleteBuildingTypeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.marspioneer.proto.DeleteBuildingTypeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

