// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MarsPioneerProto.proto

package com.example.marspioneer.proto;

public interface GetTeamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.marspioneer.proto.GetTeamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.marspioneer.proto.MPTeamProto team = 1;</code>
   * @return Whether the team field is set.
   */
  boolean hasTeam();
  /**
   * <code>.com.example.marspioneer.proto.MPTeamProto team = 1;</code>
   * @return The team.
   */
  MPTeamProto getTeam();
  /**
   * <code>.com.example.marspioneer.proto.MPTeamProto team = 1;</code>
   */
  MPTeamProtoOrBuilder getTeamOrBuilder();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.com.example.marspioneer.proto.GetTeamResponse.Status status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.com.example.marspioneer.proto.GetTeamResponse.Status status = 3;</code>
   * @return The status.
   */
  GetTeamResponse.Status getStatus();
}
