// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MarsPioneerProto.proto

package com.example.marspioneer.proto;

/**
 * Protobuf type {@code com.example.marspioneer.proto.JoinWorldResponse}
 */
public final class JoinWorldResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.marspioneer.proto.JoinWorldResponse)
    JoinWorldResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JoinWorldResponse.newBuilder() to construct.
  private JoinWorldResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JoinWorldResponse() {
    message_ = "";
    status_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new JoinWorldResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JoinWorldResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            MPPartialStateProto.Builder subBuilder = null;
            if (partialState_ != null) {
              subBuilder = partialState_.toBuilder();
            }
            partialState_ = input.readMessage(MPPartialStateProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(partialState_);
              partialState_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            MPWorldProto.Builder subBuilder = null;
            if (world_ != null) {
              subBuilder = world_.toBuilder();
            }
            world_ = input.readMessage(MPWorldProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(world_);
              world_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            MPWorldSessionProto.Builder subBuilder = null;
            if (worldSession_ != null) {
              subBuilder = worldSession_.toBuilder();
            }
            worldSession_ = input.readMessage(MPWorldSessionProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(worldSession_);
              worldSession_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MarsPioneerProto.internal_static_com_example_marspioneer_proto_JoinWorldResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MarsPioneerProto.internal_static_com_example_marspioneer_proto_JoinWorldResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            JoinWorldResponse.class, Builder.class);
  }

  /**
   * Protobuf enum {@code com.example.marspioneer.proto.JoinWorldResponse.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SERVER_ERROR = 0;</code>
     */
    SERVER_ERROR(0),
    /**
     * <code>INVALID_DATA = 1;</code>
     */
    INVALID_DATA(1),
    /**
     * <code>NOT_AUTHORIZED = 2;</code>
     */
    NOT_AUTHORIZED(2),
    /**
     * <code>NO_SUCH_WORLD = 3;</code>
     */
    NO_SUCH_WORLD(3),
    /**
     * <code>CANNOT_COMPOSE_STATE = 4;</code>
     */
    CANNOT_COMPOSE_STATE(4),
    /**
     * <code>OK = 5;</code>
     */
    OK(5),
    /**
     * <code>WORLD_FULL = 6;</code>
     */
    WORLD_FULL(6),
    /**
     * <code>PLAYER_BANNED = 7;</code>
     */
    PLAYER_BANNED(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SERVER_ERROR = 0;</code>
     */
    public static final int SERVER_ERROR_VALUE = 0;
    /**
     * <code>INVALID_DATA = 1;</code>
     */
    public static final int INVALID_DATA_VALUE = 1;
    /**
     * <code>NOT_AUTHORIZED = 2;</code>
     */
    public static final int NOT_AUTHORIZED_VALUE = 2;
    /**
     * <code>NO_SUCH_WORLD = 3;</code>
     */
    public static final int NO_SUCH_WORLD_VALUE = 3;
    /**
     * <code>CANNOT_COMPOSE_STATE = 4;</code>
     */
    public static final int CANNOT_COMPOSE_STATE_VALUE = 4;
    /**
     * <code>OK = 5;</code>
     */
    public static final int OK_VALUE = 5;
    /**
     * <code>WORLD_FULL = 6;</code>
     */
    public static final int WORLD_FULL_VALUE = 6;
    /**
     * <code>PLAYER_BANNED = 7;</code>
     */
    public static final int PLAYER_BANNED_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Status forNumber(int value) {
      switch (value) {
        case 0: return SERVER_ERROR;
        case 1: return INVALID_DATA;
        case 2: return NOT_AUTHORIZED;
        case 3: return NO_SUCH_WORLD;
        case 4: return CANNOT_COMPOSE_STATE;
        case 5: return OK;
        case 6: return WORLD_FULL;
        case 7: return PLAYER_BANNED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return JoinWorldResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.example.marspioneer.proto.JoinWorldResponse.Status)
  }

  public static final int PARTIALSTATE_FIELD_NUMBER = 1;
  private MPPartialStateProto partialState_;
  /**
   * <code>.com.example.marspioneer.proto.MPPartialStateProto partialState = 1;</code>
   * @return Whether the partialState field is set.
   */
  @Override
  public boolean hasPartialState() {
    return partialState_ != null;
  }
  /**
   * <code>.com.example.marspioneer.proto.MPPartialStateProto partialState = 1;</code>
   * @return The partialState.
   */
  @Override
  public MPPartialStateProto getPartialState() {
    return partialState_ == null ? MPPartialStateProto.getDefaultInstance() : partialState_;
  }
  /**
   * <code>.com.example.marspioneer.proto.MPPartialStateProto partialState = 1;</code>
   */
  @Override
  public MPPartialStateProtoOrBuilder getPartialStateOrBuilder() {
    return getPartialState();
  }

  public static final int WORLD_FIELD_NUMBER = 2;
  private MPWorldProto world_;
  /**
   * <code>.com.example.marspioneer.proto.MPWorldProto world = 2;</code>
   * @return Whether the world field is set.
   */
  @Override
  public boolean hasWorld() {
    return world_ != null;
  }
  /**
   * <code>.com.example.marspioneer.proto.MPWorldProto world = 2;</code>
   * @return The world.
   */
  @Override
  public MPWorldProto getWorld() {
    return world_ == null ? MPWorldProto.getDefaultInstance() : world_;
  }
  /**
   * <code>.com.example.marspioneer.proto.MPWorldProto world = 2;</code>
   */
  @Override
  public MPWorldProtoOrBuilder getWorldOrBuilder() {
    return getWorld();
  }

  public static final int WORLDSESSION_FIELD_NUMBER = 3;
  private MPWorldSessionProto worldSession_;
  /**
   * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 3;</code>
   * @return Whether the worldSession field is set.
   */
  @Override
  public boolean hasWorldSession() {
    return worldSession_ != null;
  }
  /**
   * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 3;</code>
   * @return The worldSession.
   */
  @Override
  public MPWorldSessionProto getWorldSession() {
    return worldSession_ == null ? MPWorldSessionProto.getDefaultInstance() : worldSession_;
  }
  /**
   * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 3;</code>
   */
  @Override
  public MPWorldSessionProtoOrBuilder getWorldSessionOrBuilder() {
    return getWorldSession();
  }

  public static final int MESSAGE_FIELD_NUMBER = 4;
  private volatile Object message_;
  /**
   * <code>string message = 4;</code>
   * @return The message.
   */
  @Override
  public String getMessage() {
    Object ref = message_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 4;</code>
   * @return The bytes for message.
   */
  @Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    Object ref = message_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  private int status_;
  /**
   * <code>.com.example.marspioneer.proto.JoinWorldResponse.Status status = 5;</code>
   * @return The enum numeric value on the wire for status.
   */
  @Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.com.example.marspioneer.proto.JoinWorldResponse.Status status = 5;</code>
   * @return The status.
   */
  @Override public Status getStatus() {
    @SuppressWarnings("deprecation")
    Status result = Status.valueOf(status_);
    return result == null ? Status.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (partialState_ != null) {
      output.writeMessage(1, getPartialState());
    }
    if (world_ != null) {
      output.writeMessage(2, getWorld());
    }
    if (worldSession_ != null) {
      output.writeMessage(3, getWorldSession());
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, message_);
    }
    if (status_ != Status.SERVER_ERROR.getNumber()) {
      output.writeEnum(5, status_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (partialState_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPartialState());
    }
    if (world_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getWorld());
    }
    if (worldSession_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getWorldSession());
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, message_);
    }
    if (status_ != Status.SERVER_ERROR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof JoinWorldResponse)) {
      return super.equals(obj);
    }
    JoinWorldResponse other = (JoinWorldResponse) obj;

    if (hasPartialState() != other.hasPartialState()) return false;
    if (hasPartialState()) {
      if (!getPartialState()
          .equals(other.getPartialState())) return false;
    }
    if (hasWorld() != other.hasWorld()) return false;
    if (hasWorld()) {
      if (!getWorld()
          .equals(other.getWorld())) return false;
    }
    if (hasWorldSession() != other.hasWorldSession()) return false;
    if (hasWorldSession()) {
      if (!getWorldSession()
          .equals(other.getWorldSession())) return false;
    }
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (status_ != other.status_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPartialState()) {
      hash = (37 * hash) + PARTIALSTATE_FIELD_NUMBER;
      hash = (53 * hash) + getPartialState().hashCode();
    }
    if (hasWorld()) {
      hash = (37 * hash) + WORLD_FIELD_NUMBER;
      hash = (53 * hash) + getWorld().hashCode();
    }
    if (hasWorldSession()) {
      hash = (37 * hash) + WORLDSESSION_FIELD_NUMBER;
      hash = (53 * hash) + getWorldSession().hashCode();
    }
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static JoinWorldResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JoinWorldResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JoinWorldResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JoinWorldResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JoinWorldResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JoinWorldResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JoinWorldResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static JoinWorldResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static JoinWorldResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static JoinWorldResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static JoinWorldResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static JoinWorldResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(JoinWorldResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.marspioneer.proto.JoinWorldResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.marspioneer.proto.JoinWorldResponse)
      JoinWorldResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MarsPioneerProto.internal_static_com_example_marspioneer_proto_JoinWorldResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MarsPioneerProto.internal_static_com_example_marspioneer_proto_JoinWorldResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JoinWorldResponse.class, Builder.class);
    }

    // Construct using com.example.marspioneer.proto.JoinWorldResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (partialStateBuilder_ == null) {
        partialState_ = null;
      } else {
        partialState_ = null;
        partialStateBuilder_ = null;
      }
      if (worldBuilder_ == null) {
        world_ = null;
      } else {
        world_ = null;
        worldBuilder_ = null;
      }
      if (worldSessionBuilder_ == null) {
        worldSession_ = null;
      } else {
        worldSession_ = null;
        worldSessionBuilder_ = null;
      }
      message_ = "";

      status_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MarsPioneerProto.internal_static_com_example_marspioneer_proto_JoinWorldResponse_descriptor;
    }

    @Override
    public JoinWorldResponse getDefaultInstanceForType() {
      return JoinWorldResponse.getDefaultInstance();
    }

    @Override
    public JoinWorldResponse build() {
      JoinWorldResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public JoinWorldResponse buildPartial() {
      JoinWorldResponse result = new JoinWorldResponse(this);
      if (partialStateBuilder_ == null) {
        result.partialState_ = partialState_;
      } else {
        result.partialState_ = partialStateBuilder_.build();
      }
      if (worldBuilder_ == null) {
        result.world_ = world_;
      } else {
        result.world_ = worldBuilder_.build();
      }
      if (worldSessionBuilder_ == null) {
        result.worldSession_ = worldSession_;
      } else {
        result.worldSession_ = worldSessionBuilder_.build();
      }
      result.message_ = message_;
      result.status_ = status_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof JoinWorldResponse) {
        return mergeFrom((JoinWorldResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(JoinWorldResponse other) {
      if (other == JoinWorldResponse.getDefaultInstance()) return this;
      if (other.hasPartialState()) {
        mergePartialState(other.getPartialState());
      }
      if (other.hasWorld()) {
        mergeWorld(other.getWorld());
      }
      if (other.hasWorldSession()) {
        mergeWorldSession(other.getWorldSession());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      JoinWorldResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (JoinWorldResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private MPPartialStateProto partialState_;
    private com.google.protobuf.SingleFieldBuilderV3<
        MPPartialStateProto, MPPartialStateProto.Builder, MPPartialStateProtoOrBuilder> partialStateBuilder_;
    /**
     * <code>.com.example.marspioneer.proto.MPPartialStateProto partialState = 1;</code>
     * @return Whether the partialState field is set.
     */
    public boolean hasPartialState() {
      return partialStateBuilder_ != null || partialState_ != null;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPPartialStateProto partialState = 1;</code>
     * @return The partialState.
     */
    public MPPartialStateProto getPartialState() {
      if (partialStateBuilder_ == null) {
        return partialState_ == null ? MPPartialStateProto.getDefaultInstance() : partialState_;
      } else {
        return partialStateBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.MPPartialStateProto partialState = 1;</code>
     */
    public Builder setPartialState(MPPartialStateProto value) {
      if (partialStateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        partialState_ = value;
        onChanged();
      } else {
        partialStateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPPartialStateProto partialState = 1;</code>
     */
    public Builder setPartialState(
        MPPartialStateProto.Builder builderForValue) {
      if (partialStateBuilder_ == null) {
        partialState_ = builderForValue.build();
        onChanged();
      } else {
        partialStateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPPartialStateProto partialState = 1;</code>
     */
    public Builder mergePartialState(MPPartialStateProto value) {
      if (partialStateBuilder_ == null) {
        if (partialState_ != null) {
          partialState_ =
            MPPartialStateProto.newBuilder(partialState_).mergeFrom(value).buildPartial();
        } else {
          partialState_ = value;
        }
        onChanged();
      } else {
        partialStateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPPartialStateProto partialState = 1;</code>
     */
    public Builder clearPartialState() {
      if (partialStateBuilder_ == null) {
        partialState_ = null;
        onChanged();
      } else {
        partialState_ = null;
        partialStateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPPartialStateProto partialState = 1;</code>
     */
    public MPPartialStateProto.Builder getPartialStateBuilder() {
      
      onChanged();
      return getPartialStateFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.marspioneer.proto.MPPartialStateProto partialState = 1;</code>
     */
    public MPPartialStateProtoOrBuilder getPartialStateOrBuilder() {
      if (partialStateBuilder_ != null) {
        return partialStateBuilder_.getMessageOrBuilder();
      } else {
        return partialState_ == null ?
            MPPartialStateProto.getDefaultInstance() : partialState_;
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.MPPartialStateProto partialState = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        MPPartialStateProto, MPPartialStateProto.Builder, MPPartialStateProtoOrBuilder>
        getPartialStateFieldBuilder() {
      if (partialStateBuilder_ == null) {
        partialStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            MPPartialStateProto, MPPartialStateProto.Builder, MPPartialStateProtoOrBuilder>(
                getPartialState(),
                getParentForChildren(),
                isClean());
        partialState_ = null;
      }
      return partialStateBuilder_;
    }

    private MPWorldProto world_;
    private com.google.protobuf.SingleFieldBuilderV3<
        MPWorldProto, MPWorldProto.Builder, MPWorldProtoOrBuilder> worldBuilder_;
    /**
     * <code>.com.example.marspioneer.proto.MPWorldProto world = 2;</code>
     * @return Whether the world field is set.
     */
    public boolean hasWorld() {
      return worldBuilder_ != null || world_ != null;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldProto world = 2;</code>
     * @return The world.
     */
    public MPWorldProto getWorld() {
      if (worldBuilder_ == null) {
        return world_ == null ? MPWorldProto.getDefaultInstance() : world_;
      } else {
        return worldBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldProto world = 2;</code>
     */
    public Builder setWorld(MPWorldProto value) {
      if (worldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        world_ = value;
        onChanged();
      } else {
        worldBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldProto world = 2;</code>
     */
    public Builder setWorld(
        MPWorldProto.Builder builderForValue) {
      if (worldBuilder_ == null) {
        world_ = builderForValue.build();
        onChanged();
      } else {
        worldBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldProto world = 2;</code>
     */
    public Builder mergeWorld(MPWorldProto value) {
      if (worldBuilder_ == null) {
        if (world_ != null) {
          world_ =
            MPWorldProto.newBuilder(world_).mergeFrom(value).buildPartial();
        } else {
          world_ = value;
        }
        onChanged();
      } else {
        worldBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldProto world = 2;</code>
     */
    public Builder clearWorld() {
      if (worldBuilder_ == null) {
        world_ = null;
        onChanged();
      } else {
        world_ = null;
        worldBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldProto world = 2;</code>
     */
    public MPWorldProto.Builder getWorldBuilder() {
      
      onChanged();
      return getWorldFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldProto world = 2;</code>
     */
    public MPWorldProtoOrBuilder getWorldOrBuilder() {
      if (worldBuilder_ != null) {
        return worldBuilder_.getMessageOrBuilder();
      } else {
        return world_ == null ?
            MPWorldProto.getDefaultInstance() : world_;
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldProto world = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        MPWorldProto, MPWorldProto.Builder, MPWorldProtoOrBuilder>
        getWorldFieldBuilder() {
      if (worldBuilder_ == null) {
        worldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            MPWorldProto, MPWorldProto.Builder, MPWorldProtoOrBuilder>(
                getWorld(),
                getParentForChildren(),
                isClean());
        world_ = null;
      }
      return worldBuilder_;
    }

    private MPWorldSessionProto worldSession_;
    private com.google.protobuf.SingleFieldBuilderV3<
        MPWorldSessionProto, MPWorldSessionProto.Builder, MPWorldSessionProtoOrBuilder> worldSessionBuilder_;
    /**
     * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 3;</code>
     * @return Whether the worldSession field is set.
     */
    public boolean hasWorldSession() {
      return worldSessionBuilder_ != null || worldSession_ != null;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 3;</code>
     * @return The worldSession.
     */
    public MPWorldSessionProto getWorldSession() {
      if (worldSessionBuilder_ == null) {
        return worldSession_ == null ? MPWorldSessionProto.getDefaultInstance() : worldSession_;
      } else {
        return worldSessionBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 3;</code>
     */
    public Builder setWorldSession(MPWorldSessionProto value) {
      if (worldSessionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        worldSession_ = value;
        onChanged();
      } else {
        worldSessionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 3;</code>
     */
    public Builder setWorldSession(
        MPWorldSessionProto.Builder builderForValue) {
      if (worldSessionBuilder_ == null) {
        worldSession_ = builderForValue.build();
        onChanged();
      } else {
        worldSessionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 3;</code>
     */
    public Builder mergeWorldSession(MPWorldSessionProto value) {
      if (worldSessionBuilder_ == null) {
        if (worldSession_ != null) {
          worldSession_ =
            MPWorldSessionProto.newBuilder(worldSession_).mergeFrom(value).buildPartial();
        } else {
          worldSession_ = value;
        }
        onChanged();
      } else {
        worldSessionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 3;</code>
     */
    public Builder clearWorldSession() {
      if (worldSessionBuilder_ == null) {
        worldSession_ = null;
        onChanged();
      } else {
        worldSession_ = null;
        worldSessionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 3;</code>
     */
    public MPWorldSessionProto.Builder getWorldSessionBuilder() {
      
      onChanged();
      return getWorldSessionFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 3;</code>
     */
    public MPWorldSessionProtoOrBuilder getWorldSessionOrBuilder() {
      if (worldSessionBuilder_ != null) {
        return worldSessionBuilder_.getMessageOrBuilder();
      } else {
        return worldSession_ == null ?
            MPWorldSessionProto.getDefaultInstance() : worldSession_;
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        MPWorldSessionProto, MPWorldSessionProto.Builder, MPWorldSessionProtoOrBuilder>
        getWorldSessionFieldBuilder() {
      if (worldSessionBuilder_ == null) {
        worldSessionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            MPWorldSessionProto, MPWorldSessionProto.Builder, MPWorldSessionProtoOrBuilder>(
                getWorldSession(),
                getParentForChildren(),
                isClean());
        worldSession_ = null;
      }
      return worldSessionBuilder_;
    }

    private Object message_ = "";
    /**
     * <code>string message = 4;</code>
     * @return The message.
     */
    public String getMessage() {
      Object ref = message_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string message = 4;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 4;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 4;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.com.example.marspioneer.proto.JoinWorldResponse.Status status = 5;</code>
     * @return The enum numeric value on the wire for status.
     */
    @Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.example.marspioneer.proto.JoinWorldResponse.Status status = 5;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.JoinWorldResponse.Status status = 5;</code>
     * @return The status.
     */
    @Override
    public Status getStatus() {
      @SuppressWarnings("deprecation")
      Status result = Status.valueOf(status_);
      return result == null ? Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.example.marspioneer.proto.JoinWorldResponse.Status status = 5;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.JoinWorldResponse.Status status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.marspioneer.proto.JoinWorldResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.marspioneer.proto.JoinWorldResponse)
  private static final JoinWorldResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new JoinWorldResponse();
  }

  public static JoinWorldResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JoinWorldResponse>
      PARSER = new com.google.protobuf.AbstractParser<JoinWorldResponse>() {
    @Override
    public JoinWorldResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JoinWorldResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JoinWorldResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<JoinWorldResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public JoinWorldResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

