// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MarsPioneerProto.proto

package com.example.marspioneer.proto;

public interface MPPartialStateProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.marspioneer.proto.MPPartialStateProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 1;</code>
   * @return Whether the worldSession field is set.
   */
  boolean hasWorldSession();
  /**
   * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 1;</code>
   * @return The worldSession.
   */
  MPWorldSessionProto getWorldSession();
  /**
   * <code>.com.example.marspioneer.proto.MPWorldSessionProto worldSession = 1;</code>
   */
  MPWorldSessionProtoOrBuilder getWorldSessionOrBuilder();

  /**
   * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 2;</code>
   */
  int getCellsCount();
  /**
   * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 2;</code>
   */
  boolean containsCells(
      String key);
  /**
   * Use {@link #getCellsMap()} instead.
   */
  @Deprecated
  java.util.Map<String, MPTerrainCellProto>
  getCells();
  /**
   * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 2;</code>
   */
  java.util.Map<String, MPTerrainCellProto>
  getCellsMap();
  /**
   * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 2;</code>
   */

  MPTerrainCellProto getCellsOrDefault(
      String key,
      MPTerrainCellProto defaultValue);
  /**
   * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 2;</code>
   */

  MPTerrainCellProto getCellsOrThrow(
      String key);

  /**
   * <code>map&lt;string, .com.example.marspioneer.proto.MPEntityProto&gt; entities = 3;</code>
   */
  int getEntitiesCount();
  /**
   * <code>map&lt;string, .com.example.marspioneer.proto.MPEntityProto&gt; entities = 3;</code>
   */
  boolean containsEntities(
      String key);
  /**
   * Use {@link #getEntitiesMap()} instead.
   */
  @Deprecated
  java.util.Map<String, MPEntityProto>
  getEntities();
  /**
   * <code>map&lt;string, .com.example.marspioneer.proto.MPEntityProto&gt; entities = 3;</code>
   */
  java.util.Map<String, MPEntityProto>
  getEntitiesMap();
  /**
   * <code>map&lt;string, .com.example.marspioneer.proto.MPEntityProto&gt; entities = 3;</code>
   */

  MPEntityProto getEntitiesOrDefault(
      String key,
      MPEntityProto defaultValue);
  /**
   * <code>map&lt;string, .com.example.marspioneer.proto.MPEntityProto&gt; entities = 3;</code>
   */

  MPEntityProto getEntitiesOrThrow(
      String key);
}
