// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MarsPioneerProto.proto

package com.example.marspioneer.proto;

/**
 * Protobuf type {@code com.example.marspioneer.proto.MPTerrainChunkProto}
 */
public final class MPTerrainChunkProto extends
    com.google.protobuf.GeneratedMessageV3 implements com.nkasenides.athlos.proto.Modelable<com.example.marspioneer.model.MPTerrainChunk> , com.nkasenides.athlos.model.ITerrainChunk, 
    // @@protoc_insertion_point(message_implements:com.example.marspioneer.proto.MPTerrainChunkProto)
    MPTerrainChunkProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MPTerrainChunkProto.newBuilder() to construct.
  private MPTerrainChunkProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MPTerrainChunkProto() {
    id_ = "";
    worldID_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MPTerrainChunkProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MPTerrainChunkProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            worldID_ = s;
            break;
          }
          case 26: {
            com.example.marspioneer.proto.MatrixPositionProto.Builder subBuilder = null;
            if (position_ != null) {
              subBuilder = position_.toBuilder();
            }
            position_ = input.readMessage(com.example.marspioneer.proto.MatrixPositionProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(position_);
              position_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              cells_ = com.google.protobuf.MapField.newMapField(
                  CellsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto>
            cells__ = input.readMessage(
                CellsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            cells_.getMutableMap().put(
                cells__.getKey(), cells__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_MPTerrainChunkProto_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 4:
        return internalGetCells();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_MPTerrainChunkProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.marspioneer.proto.MPTerrainChunkProto.class, com.example.marspioneer.proto.MPTerrainChunkProto.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WORLDID_FIELD_NUMBER = 2;
  private volatile java.lang.Object worldID_;
  /**
   * <code>string worldID = 2;</code>
   * @return The worldID.
   */
  @java.lang.Override
  public java.lang.String getWorldID() {
    java.lang.Object ref = worldID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      worldID_ = s;
      return s;
    }
  }
  /**
   * <code>string worldID = 2;</code>
   * @return The bytes for worldID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWorldIDBytes() {
    java.lang.Object ref = worldID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      worldID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_FIELD_NUMBER = 3;
  private com.example.marspioneer.proto.MatrixPositionProto position_;
  /**
   * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 3;</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return position_ != null;
  }
  /**
   * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 3;</code>
   * @return The position.
   */
  @java.lang.Override
  public com.example.marspioneer.proto.MatrixPositionProto getPosition() {
    return position_ == null ? com.example.marspioneer.proto.MatrixPositionProto.getDefaultInstance() : position_;
  }
  /**
   * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 3;</code>
   */
  @java.lang.Override
  public com.example.marspioneer.proto.MatrixPositionProtoOrBuilder getPositionOrBuilder() {
    return getPosition();
  }

  public static final int CELLS_FIELD_NUMBER = 4;
  private static final class CellsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto>newDefaultInstance(
                com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_MPTerrainChunkProto_CellsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.example.marspioneer.proto.MPTerrainCellProto.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto> cells_;
  private com.google.protobuf.MapField<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto>
  internalGetCells() {
    if (cells_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          CellsDefaultEntryHolder.defaultEntry);
    }
    return cells_;
  }

  public int getCellsCount() {
    return internalGetCells().getMap().size();
  }
  /**
   * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 4;</code>
   */

  @java.lang.Override
  public boolean containsCells(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetCells().getMap().containsKey(key);
  }
  /**
   * Use {@link #getCellsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto> getCells() {
    return getCellsMap();
  }
  /**
   * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 4;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto> getCellsMap() {
    return internalGetCells().getMap();
  }
  /**
   * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 4;</code>
   */
  @java.lang.Override

  public com.example.marspioneer.proto.MPTerrainCellProto getCellsOrDefault(
      java.lang.String key,
      com.example.marspioneer.proto.MPTerrainCellProto defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto> map =
        internalGetCells().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 4;</code>
   */
  @java.lang.Override

  public com.example.marspioneer.proto.MPTerrainCellProto getCellsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto> map =
        internalGetCells().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getWorldIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, worldID_);
    }
    if (position_ != null) {
      output.writeMessage(3, getPosition());
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetCells(),
        CellsDefaultEntryHolder.defaultEntry,
        4);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getWorldIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, worldID_);
    }
    if (position_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPosition());
    }
    for (java.util.Map.Entry<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto> entry
         : internalGetCells().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto>
      cells__ = CellsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, cells__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.marspioneer.proto.MPTerrainChunkProto)) {
      return super.equals(obj);
    }
    com.example.marspioneer.proto.MPTerrainChunkProto other = (com.example.marspioneer.proto.MPTerrainChunkProto) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getWorldID()
        .equals(other.getWorldID())) return false;
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (!internalGetCells().equals(
        other.internalGetCells())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + WORLDID_FIELD_NUMBER;
    hash = (53 * hash) + getWorldID().hashCode();
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    if (!internalGetCells().getMap().isEmpty()) {
      hash = (37 * hash) + CELLS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetCells().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.marspioneer.proto.MPTerrainChunkProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.marspioneer.proto.MPTerrainChunkProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.marspioneer.proto.MPTerrainChunkProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.marspioneer.proto.MPTerrainChunkProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.marspioneer.proto.MPTerrainChunkProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.marspioneer.proto.MPTerrainChunkProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.marspioneer.proto.MPTerrainChunkProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.marspioneer.proto.MPTerrainChunkProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.marspioneer.proto.MPTerrainChunkProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.marspioneer.proto.MPTerrainChunkProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.marspioneer.proto.MPTerrainChunkProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.marspioneer.proto.MPTerrainChunkProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.marspioneer.proto.MPTerrainChunkProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.marspioneer.proto.MPTerrainChunkProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements com.nkasenides.athlos.model.ITerrainChunk, com.nkasenides.athlos.proto.Modelable<com.example.marspioneer.model.MPTerrainChunk>, 
      // @@protoc_insertion_point(builder_implements:com.example.marspioneer.proto.MPTerrainChunkProto)
      com.example.marspioneer.proto.MPTerrainChunkProtoOrBuilder {    @java.lang.Override    
    public com.example.marspioneer.model.MPTerrainChunk toObject() {    
        com.example.marspioneer.model.MPTerrainChunk item = new com.example.marspioneer.model.MPTerrainChunk();        
        item.setPosition(getPosition().toObject());        
        return item;        
    }    
    

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_MPTerrainChunkProto_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetCells();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableCells();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_MPTerrainChunkProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.marspioneer.proto.MPTerrainChunkProto.class, com.example.marspioneer.proto.MPTerrainChunkProto.Builder.class);
    }

    // Construct using com.example.marspioneer.proto.MPTerrainChunkProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      worldID_ = "";

      if (positionBuilder_ == null) {
        position_ = null;
      } else {
        position_ = null;
        positionBuilder_ = null;
      }
      internalGetMutableCells().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_MPTerrainChunkProto_descriptor;
    }

    @java.lang.Override
    public com.example.marspioneer.proto.MPTerrainChunkProto getDefaultInstanceForType() {
      return com.example.marspioneer.proto.MPTerrainChunkProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.marspioneer.proto.MPTerrainChunkProto build() {
      com.example.marspioneer.proto.MPTerrainChunkProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.marspioneer.proto.MPTerrainChunkProto buildPartial() {
      com.example.marspioneer.proto.MPTerrainChunkProto result = new com.example.marspioneer.proto.MPTerrainChunkProto(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.worldID_ = worldID_;
      if (positionBuilder_ == null) {
        result.position_ = position_;
      } else {
        result.position_ = positionBuilder_.build();
      }
      result.cells_ = internalGetCells();
      result.cells_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.marspioneer.proto.MPTerrainChunkProto) {
        return mergeFrom((com.example.marspioneer.proto.MPTerrainChunkProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.marspioneer.proto.MPTerrainChunkProto other) {
      if (other == com.example.marspioneer.proto.MPTerrainChunkProto.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getWorldID().isEmpty()) {
        worldID_ = other.worldID_;
        onChanged();
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      internalGetMutableCells().mergeFrom(
          other.internalGetCells());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.marspioneer.proto.MPTerrainChunkProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.marspioneer.proto.MPTerrainChunkProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object worldID_ = "";
    /**
     * <code>string worldID = 2;</code>
     * @return The worldID.
     */
    public java.lang.String getWorldID() {
      java.lang.Object ref = worldID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        worldID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string worldID = 2;</code>
     * @return The bytes for worldID.
     */
    public com.google.protobuf.ByteString
        getWorldIDBytes() {
      java.lang.Object ref = worldID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        worldID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string worldID = 2;</code>
     * @param value The worldID to set.
     * @return This builder for chaining.
     */
    public Builder setWorldID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      worldID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string worldID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorldID() {
      
      worldID_ = getDefaultInstance().getWorldID();
      onChanged();
      return this;
    }
    /**
     * <code>string worldID = 2;</code>
     * @param value The bytes for worldID to set.
     * @return This builder for chaining.
     */
    public Builder setWorldIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      worldID_ = value;
      onChanged();
      return this;
    }

    private com.example.marspioneer.proto.MatrixPositionProto position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.marspioneer.proto.MatrixPositionProto, com.example.marspioneer.proto.MatrixPositionProto.Builder, com.example.marspioneer.proto.MatrixPositionProtoOrBuilder> positionBuilder_;
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 3;</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return positionBuilder_ != null || position_ != null;
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 3;</code>
     * @return The position.
     */
    public com.example.marspioneer.proto.MatrixPositionProto getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? com.example.marspioneer.proto.MatrixPositionProto.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 3;</code>
     */
    public Builder setPosition(com.example.marspioneer.proto.MatrixPositionProto value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
        onChanged();
      } else {
        positionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 3;</code>
     */
    public Builder setPosition(
        com.example.marspioneer.proto.MatrixPositionProto.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
        onChanged();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 3;</code>
     */
    public Builder mergePosition(com.example.marspioneer.proto.MatrixPositionProto value) {
      if (positionBuilder_ == null) {
        if (position_ != null) {
          position_ =
            com.example.marspioneer.proto.MatrixPositionProto.newBuilder(position_).mergeFrom(value).buildPartial();
        } else {
          position_ = value;
        }
        onChanged();
      } else {
        positionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 3;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        position_ = null;
        onChanged();
      } else {
        position_ = null;
        positionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 3;</code>
     */
    public com.example.marspioneer.proto.MatrixPositionProto.Builder getPositionBuilder() {
      
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 3;</code>
     */
    public com.example.marspioneer.proto.MatrixPositionProtoOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            com.example.marspioneer.proto.MatrixPositionProto.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.MatrixPositionProto position = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.marspioneer.proto.MatrixPositionProto, com.example.marspioneer.proto.MatrixPositionProto.Builder, com.example.marspioneer.proto.MatrixPositionProtoOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.marspioneer.proto.MatrixPositionProto, com.example.marspioneer.proto.MatrixPositionProto.Builder, com.example.marspioneer.proto.MatrixPositionProtoOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto> cells_;
    private com.google.protobuf.MapField<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto>
    internalGetCells() {
      if (cells_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CellsDefaultEntryHolder.defaultEntry);
      }
      return cells_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto>
    internalGetMutableCells() {
      onChanged();;
      if (cells_ == null) {
        cells_ = com.google.protobuf.MapField.newMapField(
            CellsDefaultEntryHolder.defaultEntry);
      }
      if (!cells_.isMutable()) {
        cells_ = cells_.copy();
      }
      return cells_;
    }

    public int getCellsCount() {
      return internalGetCells().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 4;</code>
     */

    @java.lang.Override
    public boolean containsCells(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetCells().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCellsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto> getCells() {
      return getCellsMap();
    }
    /**
     * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 4;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto> getCellsMap() {
      return internalGetCells().getMap();
    }
    /**
     * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 4;</code>
     */
    @java.lang.Override

    public com.example.marspioneer.proto.MPTerrainCellProto getCellsOrDefault(
        java.lang.String key,
        com.example.marspioneer.proto.MPTerrainCellProto defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto> map =
          internalGetCells().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 4;</code>
     */
    @java.lang.Override

    public com.example.marspioneer.proto.MPTerrainCellProto getCellsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto> map =
          internalGetCells().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearCells() {
      internalGetMutableCells().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 4;</code>
     */

    public Builder removeCells(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableCells().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto>
    getMutableCells() {
      return internalGetMutableCells().getMutableMap();
    }
    /**
     * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 4;</code>
     */
    public Builder putCells(
        java.lang.String key,
        com.example.marspioneer.proto.MPTerrainCellProto value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableCells().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .com.example.marspioneer.proto.MPTerrainCellProto&gt; cells = 4;</code>
     */

    public Builder putAllCells(
        java.util.Map<java.lang.String, com.example.marspioneer.proto.MPTerrainCellProto> values) {
      internalGetMutableCells().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.marspioneer.proto.MPTerrainChunkProto)
  }

  // @@protoc_insertion_point(class_scope:com.example.marspioneer.proto.MPTerrainChunkProto)
  private static final com.example.marspioneer.proto.MPTerrainChunkProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.marspioneer.proto.MPTerrainChunkProto();
  }

  public static com.example.marspioneer.proto.MPTerrainChunkProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MPTerrainChunkProto>
      PARSER = new com.google.protobuf.AbstractParser<MPTerrainChunkProto>() {
    @java.lang.Override
    public MPTerrainChunkProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MPTerrainChunkProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MPTerrainChunkProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MPTerrainChunkProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.marspioneer.proto.MPTerrainChunkProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

    @java.lang.Override    
    public com.example.marspioneer.model.MPTerrainChunk toObject() {    
        com.example.marspioneer.model.MPTerrainChunk item = new com.example.marspioneer.model.MPTerrainChunk();        
        item.setPosition(getPosition().toObject());        
        return item;        
    }    
    
}

