// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/MarsPioneerProto.proto

package com.example.marspioneer.proto;

/**
 * Protobuf type {@code com.example.marspioneer.proto.UpdateBuildingTypeRequest}
 */
public final class UpdateBuildingTypeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.marspioneer.proto.UpdateBuildingTypeRequest)
    UpdateBuildingTypeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateBuildingTypeRequest.newBuilder() to construct.
  private UpdateBuildingTypeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateBuildingTypeRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateBuildingTypeRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateBuildingTypeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.example.marspioneer.proto.MPGameSessionProto.Builder subBuilder = null;
            if (gameSessionID_ != null) {
              subBuilder = gameSessionID_.toBuilder();
            }
            gameSessionID_ = input.readMessage(com.example.marspioneer.proto.MPGameSessionProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(gameSessionID_);
              gameSessionID_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.example.marspioneer.proto.BuildingTypeProto.Builder subBuilder = null;
            if (buildingType_ != null) {
              subBuilder = buildingType_.toBuilder();
            }
            buildingType_ = input.readMessage(com.example.marspioneer.proto.BuildingTypeProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(buildingType_);
              buildingType_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_UpdateBuildingTypeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_UpdateBuildingTypeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.marspioneer.proto.UpdateBuildingTypeRequest.class, com.example.marspioneer.proto.UpdateBuildingTypeRequest.Builder.class);
  }

  public static final int GAMESESSIONID_FIELD_NUMBER = 1;
  private com.example.marspioneer.proto.MPGameSessionProto gameSessionID_;
  /**
   * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
   * @return Whether the gameSessionID field is set.
   */
  @java.lang.Override
  public boolean hasGameSessionID() {
    return gameSessionID_ != null;
  }
  /**
   * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
   * @return The gameSessionID.
   */
  @java.lang.Override
  public com.example.marspioneer.proto.MPGameSessionProto getGameSessionID() {
    return gameSessionID_ == null ? com.example.marspioneer.proto.MPGameSessionProto.getDefaultInstance() : gameSessionID_;
  }
  /**
   * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
   */
  @java.lang.Override
  public com.example.marspioneer.proto.MPGameSessionProtoOrBuilder getGameSessionIDOrBuilder() {
    return getGameSessionID();
  }

  public static final int BUILDINGTYPE_FIELD_NUMBER = 2;
  private com.example.marspioneer.proto.BuildingTypeProto buildingType_;
  /**
   * <code>.com.example.marspioneer.proto.BuildingTypeProto buildingType = 2;</code>
   * @return Whether the buildingType field is set.
   */
  @java.lang.Override
  public boolean hasBuildingType() {
    return buildingType_ != null;
  }
  /**
   * <code>.com.example.marspioneer.proto.BuildingTypeProto buildingType = 2;</code>
   * @return The buildingType.
   */
  @java.lang.Override
  public com.example.marspioneer.proto.BuildingTypeProto getBuildingType() {
    return buildingType_ == null ? com.example.marspioneer.proto.BuildingTypeProto.getDefaultInstance() : buildingType_;
  }
  /**
   * <code>.com.example.marspioneer.proto.BuildingTypeProto buildingType = 2;</code>
   */
  @java.lang.Override
  public com.example.marspioneer.proto.BuildingTypeProtoOrBuilder getBuildingTypeOrBuilder() {
    return getBuildingType();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (gameSessionID_ != null) {
      output.writeMessage(1, getGameSessionID());
    }
    if (buildingType_ != null) {
      output.writeMessage(2, getBuildingType());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (gameSessionID_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGameSessionID());
    }
    if (buildingType_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBuildingType());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.marspioneer.proto.UpdateBuildingTypeRequest)) {
      return super.equals(obj);
    }
    com.example.marspioneer.proto.UpdateBuildingTypeRequest other = (com.example.marspioneer.proto.UpdateBuildingTypeRequest) obj;

    if (hasGameSessionID() != other.hasGameSessionID()) return false;
    if (hasGameSessionID()) {
      if (!getGameSessionID()
          .equals(other.getGameSessionID())) return false;
    }
    if (hasBuildingType() != other.hasBuildingType()) return false;
    if (hasBuildingType()) {
      if (!getBuildingType()
          .equals(other.getBuildingType())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGameSessionID()) {
      hash = (37 * hash) + GAMESESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getGameSessionID().hashCode();
    }
    if (hasBuildingType()) {
      hash = (37 * hash) + BUILDINGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingType().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.marspioneer.proto.UpdateBuildingTypeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.marspioneer.proto.UpdateBuildingTypeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.marspioneer.proto.UpdateBuildingTypeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.marspioneer.proto.UpdateBuildingTypeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.marspioneer.proto.UpdateBuildingTypeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.marspioneer.proto.UpdateBuildingTypeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.marspioneer.proto.UpdateBuildingTypeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.marspioneer.proto.UpdateBuildingTypeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.marspioneer.proto.UpdateBuildingTypeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.marspioneer.proto.UpdateBuildingTypeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.marspioneer.proto.UpdateBuildingTypeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.marspioneer.proto.UpdateBuildingTypeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.marspioneer.proto.UpdateBuildingTypeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.marspioneer.proto.UpdateBuildingTypeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.marspioneer.proto.UpdateBuildingTypeRequest)
      com.example.marspioneer.proto.UpdateBuildingTypeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_UpdateBuildingTypeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_UpdateBuildingTypeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.marspioneer.proto.UpdateBuildingTypeRequest.class, com.example.marspioneer.proto.UpdateBuildingTypeRequest.Builder.class);
    }

    // Construct using com.example.marspioneer.proto.UpdateBuildingTypeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (gameSessionIDBuilder_ == null) {
        gameSessionID_ = null;
      } else {
        gameSessionID_ = null;
        gameSessionIDBuilder_ = null;
      }
      if (buildingTypeBuilder_ == null) {
        buildingType_ = null;
      } else {
        buildingType_ = null;
        buildingTypeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.marspioneer.proto.MarsPioneerProto.internal_static_com_example_marspioneer_proto_UpdateBuildingTypeRequest_descriptor;
    }

    @java.lang.Override
    public com.example.marspioneer.proto.UpdateBuildingTypeRequest getDefaultInstanceForType() {
      return com.example.marspioneer.proto.UpdateBuildingTypeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.marspioneer.proto.UpdateBuildingTypeRequest build() {
      com.example.marspioneer.proto.UpdateBuildingTypeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.marspioneer.proto.UpdateBuildingTypeRequest buildPartial() {
      com.example.marspioneer.proto.UpdateBuildingTypeRequest result = new com.example.marspioneer.proto.UpdateBuildingTypeRequest(this);
      if (gameSessionIDBuilder_ == null) {
        result.gameSessionID_ = gameSessionID_;
      } else {
        result.gameSessionID_ = gameSessionIDBuilder_.build();
      }
      if (buildingTypeBuilder_ == null) {
        result.buildingType_ = buildingType_;
      } else {
        result.buildingType_ = buildingTypeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.marspioneer.proto.UpdateBuildingTypeRequest) {
        return mergeFrom((com.example.marspioneer.proto.UpdateBuildingTypeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.marspioneer.proto.UpdateBuildingTypeRequest other) {
      if (other == com.example.marspioneer.proto.UpdateBuildingTypeRequest.getDefaultInstance()) return this;
      if (other.hasGameSessionID()) {
        mergeGameSessionID(other.getGameSessionID());
      }
      if (other.hasBuildingType()) {
        mergeBuildingType(other.getBuildingType());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.marspioneer.proto.UpdateBuildingTypeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.marspioneer.proto.UpdateBuildingTypeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.example.marspioneer.proto.MPGameSessionProto gameSessionID_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.marspioneer.proto.MPGameSessionProto, com.example.marspioneer.proto.MPGameSessionProto.Builder, com.example.marspioneer.proto.MPGameSessionProtoOrBuilder> gameSessionIDBuilder_;
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     * @return Whether the gameSessionID field is set.
     */
    public boolean hasGameSessionID() {
      return gameSessionIDBuilder_ != null || gameSessionID_ != null;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     * @return The gameSessionID.
     */
    public com.example.marspioneer.proto.MPGameSessionProto getGameSessionID() {
      if (gameSessionIDBuilder_ == null) {
        return gameSessionID_ == null ? com.example.marspioneer.proto.MPGameSessionProto.getDefaultInstance() : gameSessionID_;
      } else {
        return gameSessionIDBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     */
    public Builder setGameSessionID(com.example.marspioneer.proto.MPGameSessionProto value) {
      if (gameSessionIDBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gameSessionID_ = value;
        onChanged();
      } else {
        gameSessionIDBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     */
    public Builder setGameSessionID(
        com.example.marspioneer.proto.MPGameSessionProto.Builder builderForValue) {
      if (gameSessionIDBuilder_ == null) {
        gameSessionID_ = builderForValue.build();
        onChanged();
      } else {
        gameSessionIDBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     */
    public Builder mergeGameSessionID(com.example.marspioneer.proto.MPGameSessionProto value) {
      if (gameSessionIDBuilder_ == null) {
        if (gameSessionID_ != null) {
          gameSessionID_ =
            com.example.marspioneer.proto.MPGameSessionProto.newBuilder(gameSessionID_).mergeFrom(value).buildPartial();
        } else {
          gameSessionID_ = value;
        }
        onChanged();
      } else {
        gameSessionIDBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     */
    public Builder clearGameSessionID() {
      if (gameSessionIDBuilder_ == null) {
        gameSessionID_ = null;
        onChanged();
      } else {
        gameSessionID_ = null;
        gameSessionIDBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     */
    public com.example.marspioneer.proto.MPGameSessionProto.Builder getGameSessionIDBuilder() {
      
      onChanged();
      return getGameSessionIDFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     */
    public com.example.marspioneer.proto.MPGameSessionProtoOrBuilder getGameSessionIDOrBuilder() {
      if (gameSessionIDBuilder_ != null) {
        return gameSessionIDBuilder_.getMessageOrBuilder();
      } else {
        return gameSessionID_ == null ?
            com.example.marspioneer.proto.MPGameSessionProto.getDefaultInstance() : gameSessionID_;
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.MPGameSessionProto gameSessionID = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.marspioneer.proto.MPGameSessionProto, com.example.marspioneer.proto.MPGameSessionProto.Builder, com.example.marspioneer.proto.MPGameSessionProtoOrBuilder> 
        getGameSessionIDFieldBuilder() {
      if (gameSessionIDBuilder_ == null) {
        gameSessionIDBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.marspioneer.proto.MPGameSessionProto, com.example.marspioneer.proto.MPGameSessionProto.Builder, com.example.marspioneer.proto.MPGameSessionProtoOrBuilder>(
                getGameSessionID(),
                getParentForChildren(),
                isClean());
        gameSessionID_ = null;
      }
      return gameSessionIDBuilder_;
    }

    private com.example.marspioneer.proto.BuildingTypeProto buildingType_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.marspioneer.proto.BuildingTypeProto, com.example.marspioneer.proto.BuildingTypeProto.Builder, com.example.marspioneer.proto.BuildingTypeProtoOrBuilder> buildingTypeBuilder_;
    /**
     * <code>.com.example.marspioneer.proto.BuildingTypeProto buildingType = 2;</code>
     * @return Whether the buildingType field is set.
     */
    public boolean hasBuildingType() {
      return buildingTypeBuilder_ != null || buildingType_ != null;
    }
    /**
     * <code>.com.example.marspioneer.proto.BuildingTypeProto buildingType = 2;</code>
     * @return The buildingType.
     */
    public com.example.marspioneer.proto.BuildingTypeProto getBuildingType() {
      if (buildingTypeBuilder_ == null) {
        return buildingType_ == null ? com.example.marspioneer.proto.BuildingTypeProto.getDefaultInstance() : buildingType_;
      } else {
        return buildingTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.BuildingTypeProto buildingType = 2;</code>
     */
    public Builder setBuildingType(com.example.marspioneer.proto.BuildingTypeProto value) {
      if (buildingTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        buildingType_ = value;
        onChanged();
      } else {
        buildingTypeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.BuildingTypeProto buildingType = 2;</code>
     */
    public Builder setBuildingType(
        com.example.marspioneer.proto.BuildingTypeProto.Builder builderForValue) {
      if (buildingTypeBuilder_ == null) {
        buildingType_ = builderForValue.build();
        onChanged();
      } else {
        buildingTypeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.BuildingTypeProto buildingType = 2;</code>
     */
    public Builder mergeBuildingType(com.example.marspioneer.proto.BuildingTypeProto value) {
      if (buildingTypeBuilder_ == null) {
        if (buildingType_ != null) {
          buildingType_ =
            com.example.marspioneer.proto.BuildingTypeProto.newBuilder(buildingType_).mergeFrom(value).buildPartial();
        } else {
          buildingType_ = value;
        }
        onChanged();
      } else {
        buildingTypeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.BuildingTypeProto buildingType = 2;</code>
     */
    public Builder clearBuildingType() {
      if (buildingTypeBuilder_ == null) {
        buildingType_ = null;
        onChanged();
      } else {
        buildingType_ = null;
        buildingTypeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.marspioneer.proto.BuildingTypeProto buildingType = 2;</code>
     */
    public com.example.marspioneer.proto.BuildingTypeProto.Builder getBuildingTypeBuilder() {
      
      onChanged();
      return getBuildingTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.marspioneer.proto.BuildingTypeProto buildingType = 2;</code>
     */
    public com.example.marspioneer.proto.BuildingTypeProtoOrBuilder getBuildingTypeOrBuilder() {
      if (buildingTypeBuilder_ != null) {
        return buildingTypeBuilder_.getMessageOrBuilder();
      } else {
        return buildingType_ == null ?
            com.example.marspioneer.proto.BuildingTypeProto.getDefaultInstance() : buildingType_;
      }
    }
    /**
     * <code>.com.example.marspioneer.proto.BuildingTypeProto buildingType = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.marspioneer.proto.BuildingTypeProto, com.example.marspioneer.proto.BuildingTypeProto.Builder, com.example.marspioneer.proto.BuildingTypeProtoOrBuilder> 
        getBuildingTypeFieldBuilder() {
      if (buildingTypeBuilder_ == null) {
        buildingTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.marspioneer.proto.BuildingTypeProto, com.example.marspioneer.proto.BuildingTypeProto.Builder, com.example.marspioneer.proto.BuildingTypeProtoOrBuilder>(
                getBuildingType(),
                getParentForChildren(),
                isClean());
        buildingType_ = null;
      }
      return buildingTypeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.marspioneer.proto.UpdateBuildingTypeRequest)
  }

  // @@protoc_insertion_point(class_scope:com.example.marspioneer.proto.UpdateBuildingTypeRequest)
  private static final com.example.marspioneer.proto.UpdateBuildingTypeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.marspioneer.proto.UpdateBuildingTypeRequest();
  }

  public static com.example.marspioneer.proto.UpdateBuildingTypeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateBuildingTypeRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateBuildingTypeRequest>() {
    @java.lang.Override
    public UpdateBuildingTypeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateBuildingTypeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateBuildingTypeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateBuildingTypeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.marspioneer.proto.UpdateBuildingTypeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

