/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Project Editor, v1.0 BETA
-------------------------------------------------------------------------------- */

package com.example.marspioneer.service;
import com.example.marspioneer.model.MPPlayer;
import com.example.marspioneer.model.MPWorldSession;
import com.example.marspioneer.persistence.DBManager;
import com.example.marspioneer.proto.JoinWorldResponse;
import com.nkasenides.athlos.backend.AthlosService;
import com.example.marspioneer.proto.LeaveWorldRequest;
import com.example.marspioneer.auth.*;
import com.example.marspioneer.proto.LeaveWorldResponse;

public class LeaveWorld implements AthlosService<LeaveWorldRequest, LeaveWorldResponse> {

    @Override    
    public LeaveWorldResponse serve(LeaveWorldRequest request, Object... additionalParams) {

        //Verify world session:
        final MPPlayer player = Auth.verifyWorldSessionID(request.getWorldSessionID());
        if (player == null) {
            return LeaveWorldResponse.newBuilder()
                    .setStatus(LeaveWorldResponse.Status.NOT_AUTHORIZED)
                    .setMessage("NOT_AUTHORIZED")
                    .build();
        }

        //Get the world session:
        final MPWorldSession worldSession = DBManager.worldSession.get(request.getWorldSessionID());
        DBManager.worldSession.delete(worldSession);

        return LeaveWorldResponse.newBuilder()
                .setStatus(LeaveWorldResponse.Status.OK)
                .setMessage("OK")
                .build();

    }    
    
}

