///* --------------------------------------------------------------------------------
//  This file was automatically generated by the Athlos Project Editor.
//  Athlos Project Editor, v1.0 BETA
//-------------------------------------------------------------------------------- */
//
//package com.example.marspioneer.service;
//import com.nkasenides.athlos.backend.AthlosService;
//import com.example.marspioneer.proto.ListTeamsRequest;
//import com.example.marspioneer.auth.*;
//import com.example.marspioneer.proto.ListTeamsResponse;
//
//public class ListTeams implements AthlosService<ListTeamsRequest, ListTeamsResponse> {
//
//    @Override
//    public ListTeamsResponse serve(ListTeamsRequest request, Object... additionalParams) {
//
//
//
//    }
//
//}
//
