/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Project Editor, v1.0 BETA
-------------------------------------------------------------------------------- */

package com.example.marspioneer.service;
import com.nkasenides.athlos.backend.AthlosService;
import com.example.marspioneer.proto.UpdatePlayerRequest;
import com.example.marspioneer.auth.*;
import com.example.marspioneer.proto.UpdatePlayerResponse;

public class UpdatePlayer implements AthlosService<UpdatePlayerRequest, UpdatePlayerResponse> {

    @Override    
    public UpdatePlayerResponse serve(UpdatePlayerRequest request, Object... additionalParams) {    
        //TODO - Implement this service.        
        return null;        
    }    
    
}

