runtime: java
env: flex
handlers:
  - url: /.*
    script: this field is required, but ignored
resources:
  cpu: 4
  memory_gb: 4
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.5
  target_concurrent_requests: 30
env_variables:
  JETTY_MODULES_ENABLE: websocket