/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Project Editor, v1.0 BETA
-------------------------------------------------------------------------------- */

package com.example.marspioneer.model;

import com.nkasenides.athlos.proto.Transmittable;
import com.example.marspioneer.proto.*;
import com.nkasenides.athlos.model.*;
import com.raylabz.firestorm.annotation.FirestormObject;
import com.raylabz.objectis.annotation.ObjectisObject;

import java.io.Serializable;

@FirestormObject
@ObjectisObject
public class BuildingEntity implements MPEntity {
    private String worldID;    
    private float areaOfInterest;    
    private String id;    
    private MatrixPosition position;    
    private EBuildingType buildingType;    
    private String playerID;    
    private Direction4 direction;    

    public String getWorldID() {    
        return worldID;        
    }    
    
    public float getAreaOfInterest() {    
        return areaOfInterest;        
    }    
    
    public String getId() {    
        return id;        
    }    
    
    public MatrixPosition getPosition() {    
        return position;        
    }    
    
    public EBuildingType getBuildingType() {    
        return buildingType;        
    }    
    
    public String getPlayerID() {    
        return playerID;        
    }    
    
    public Direction4 getDirection() {    
        return direction;        
    }    
    

    public void setWorldID(String worldID) {    
        this.worldID = worldID;        
    }    
    
    public void setAreaOfInterest(float areaOfInterest) {    
        this.areaOfInterest = areaOfInterest;        
    }    
    
    public void setId(String id) {    
        this.id = id;        
    }    
    
    public void setPosition(MatrixPosition position) {    
        this.position = position;        
    }    
    
    public void setBuildingType(EBuildingType buildingType) {    
        this.buildingType = buildingType;        
    }    
    
    public void setPlayerID(String playerID) {    
        this.playerID = playerID;        
    }    
    
    public void setDirection(Direction4 direction) {    
        this.direction = direction;        
    }    
    

    @Override    
    public com.example.marspioneer.proto.MPEntityProto.Builder toProto() {    
        com.example.marspioneer.proto.BuildingEntityProto.Builder protoBuilder = com.example.marspioneer.proto.BuildingEntityProto.newBuilder();
        protoBuilder.setWorldID(worldID);
        protoBuilder.setAreaOfInterest(areaOfInterest);
        protoBuilder.setId(id);
        protoBuilder.setPosition(position.toProto().build());
        protoBuilder.setBuildingType(buildingType);
        protoBuilder.setPlayerID(playerID);
        protoBuilder.setDirection(direction);
        return MPEntityProto.newBuilder()        
                .setBuildingEntity(protoBuilder.build())                
                .setWorldID(worldID)                
                .setAreaOfInterest(areaOfInterest)                
                .setId(id)                
                .setPosition(position.toProto().build())                
                .setPlayerID(playerID)                
                .setDirection(direction)                
                ;                
        }        

}
