/* --------------------------------------------------------------------------------
  This file was automatically generated by the Athlos Project Editor.
  Athlos Project Editor, v1.0 BETA
-------------------------------------------------------------------------------- */

package com.example.marspioneer.client.websocket;

import com.example.marspioneer.client.MPClient;
import com.example.marspioneer.proto.BuildResponse;
import com.google.protobuf.InvalidProtocolBufferException;
import com.neovisionaries.ws.client.WebSocketException;
import com.raylabz.mocha.binary.client.BinaryWebSocketClient;

import java.io.IOException;

public class BuildSandPitStub extends BinaryWebSocketClient {

    private MPClient client;

    public BuildSandPitStub(MPClient client) throws IOException, WebSocketException {
        super("ws://localhost:8080/api/action/buildSandPit");
        this.client = client;
    }

    @Override
    public void onReceive(byte[] bytes) {
        try {
            BuildResponse response = BuildResponse.parseFrom(bytes);
            handleResponse(response);
        } catch (InvalidProtocolBufferException e) {
            e.printStackTrace();
            //TODO - Handle exception
        }
    }
    
    public void handleResponse(BuildResponse response) {
        //TODO - Implement handling of the response.
    }

}

